### PR TITLE
Resolves #53

### LINKED ISSUE #53: Utils.readJson(String, JsonObject, int) performance improvements
instead of throwing exceptions. It can return a `Result` object as follows
```java
public class Result {
  @Nullable;
  String error;
  int code;
  @Nullable;
  JsonElement result;
}
```

### PR DESCRIPTION
**Pull request by adityasharat**

### CODE REVIEW

File: library/src/main/java/com/flipkart/layoutengine/DataContext.java [hunk 1]
```diff
@@ -119,13 +108,8 @@ public void setDataProvider(JsonProvider dataProvider) {
...
         String aliasedDataPath = getAliasedDataPath(dataPath, reverseScope, true);
-        try {
-            return Utils.getElementFromData(aliasedDataPath, dataProvider, childIndex);
-        } catch (JsonNullException e) {
-            return JsonNull.INSTANCE;
-        } catch (NoSuchDataPathException | InvalidDataPathException e) {
-            return null;
-        }
+        Result result = Utils.getElementFromData(aliasedDataPath, dataProvider, childIndex);
+        return result.isSuccess() ? result.element : null;
```
Comment (yasirmhd) [inline library/src/main/java/com/flipkart/layoutengine/DataContext.java]: What about JsonNullException case?

File: library/src/main/java/com/flipkart/layoutengine/builder/DataParsingLayoutBuilder.java [hunk 2]
```diff
@@ -233,27 +205,17 @@ private JsonElement findAndReplaceValues(JsonElement element, ParserContext pars
...
-                            formattedValue = format(Utils.getElementFromData(dataPath,
-                                    parserContext.getDataContext().getDataProvider(),
-                                    parserContext.getDataContext().getIndex()),
-                                    formatterName);
-                        } catch (JsonNullException | NoSuchDataPathException | InvalidDataPathException e) {
-                            if (ProteusConstants.isLoggingEnabled()) {
-                                logger.error(TAG_ERROR + "#findAndReplaceValues() " + e.getMessage());
-                            }
+                        result = Utils.getElementFromData(dataPath, parserContext.getDataContext().getDataProvider(), parserContext.getDataContext().getIndex());
+                        if (result.isSuccess() && null != result.element) {
```
Comment (yasirmhd) [inline library/src/main/java/com/flipkart/layoutengine/builder/DataParsingLayoutBuilder.java]: do you need null != result.element? It wasn't there earlier.

Comment (adityasharat) [inline library/src/main/java/com/flipkart/layoutengine/builder/DataParsingLayoutBuilder.java]: since `Result.element` is `@Nullable` it gives a warning. I could remove it, because `Result.isSuccess` kind of guarantees that `Result.element` will not be `null`.

File: library/src/main/java/com/flipkart/layoutengine/view/DataProteusView.java [hunk 3]
```diff
@@ -269,18 +252,10 @@ public void set(String dataPath, JsonElement newValue, int childIndex) {
...
-        JsonElement parent = null;
-        try {
-            parent = Utils.getElementFromData(aliasedDataPath.substring(0, aliasedDataPath.lastIndexOf(".")),
-                    parserContext.getDataContext().getDataProvider(), childIndex);
-        } catch (JsonNullException | NoSuchDataPathException | InvalidDataPathException e) {
-            if (ProteusConstants.isLoggingEnabled()) {
-                logger.error("#set() " + e.getMessage());
-            }
-        }
+        Result result = Utils.getElementFromData(aliasedDataPath.substring(0, aliasedDataPath.lastIndexOf(".")), parserContext.getDataContext().getDataProvider(), childIndex);
```
Comment (yasirmhd) [inline library/src/main/java/com/flipkart/layoutengine/view/DataProteusView.java]: Can you please make "." as final static string? This will get called so many times so it is better it gets initialized only once.

File: library/src/main/java/com/flipkart/layoutengine/DataContext.java (hunk 1 above)
Comment (adityasharat) [inline library/src/main/java/com/flipkart/layoutengine/DataContext.java]: Nice catch, fixing this now.

File: library/src/main/java/com/flipkart/layoutengine/view/DataProteusView.java (hunk 3 above)
Comment (adityasharat) [inline library/src/main/java/com/flipkart/layoutengine/view/DataProteusView.java]: Understood, will do so.

**Comment by yasirmhd** [comment]
LGTM

**Comment by thekirankumar** [comment]
LGTM
